# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('full_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('full_address', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('name_slug', models.SlugField()),
                ('opening_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True)),
                ('history', models.TextField(null=True)),
            ],
        ),
    ]
